language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: kcU7DRNA7DKFON/VtAjI4UQD5KiJUvnYfiJOimKhT/G84AvN+AG7AkhCT1ohQlAJuusddTQ/TsCVUDIz3PvWz3/B23uYxzbuCT/Wj3qtiPAWwf4SYtindOE4cncKr+6UB8vSemH3iToRDdYNALabKJoTpiEiX4D+5MwZmh8JWlCiaE0EPjdcSYh7W9WOnfwRHGzlUG4D4YnVLPGwDtAubZYqdO8BJ2ZwUBCbaC7Yjni8IQ1IqbTbZcVfoL0HfyAd77Tf4Jb8URVPylIozO8EEmBU6DaQ36ZGCYH7hT958E6lmb4eblvlOBplTRmfS97sNczs3VxSQ1pSCkacQ2xzrHw1NOo7xj9WfgSA0b1vPGXUXvZ9qsEREeGqTw/gwe6e8IOm8Re/a7WIVmdHbIqrwjzAZln1bm+vLgxEGUuk5t5Ozhv4/0lG6JIMwDyXzcD8orKo+Q9GLWvTXiacRQIDC2NLgB/PYKD6pAcgrM384/iY+cuqAkpG256TSq/NV3fRHqw/KkR071xBPXB6k0e9R/3iwCVFPnxvpfd0JqYfCnO8n4LYzl+8oBN9SXiGYK3V/eLaewJw3ZRpk1Od309YQfwzG+2FBbpjBNyJT+E6jVndVTU5lveqLCOwqYo+cmvB0RasV8MZ4mtYBcSVWAB+eSjtDKupbNlKXT/cn+IqJ8k=
  app: powerful-bastion-28057